name: Deploy Node Application

on: 
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Source
        uses: actions/checkout@v4
      
      - name: Login to Docker Hub
        run: echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u ${{ secrets.DOCKER_USERNAME }} --password-stdin
        
      - name: Build Docker Image
        run: docker build -t asghar0017/nodejs-app:latest .
      
      - name: Publish Image to Docker Hub
        run: docker push asghar0017/nodejs-app:latest

  deploy:
    runs-on: self-hosted
    steps:
      - name: Pull Docker Image
        run: docker pull asghar0017/nodejs-app:latest

      - name: Delete Old Container
        run: docker rm -f nodejs-app-container || true

      - name: Run Docker Container
        run: |
          docker run -d -p 3001:3001 --name nodejs-app-container \
            -e MONGO_PASSWORD="mongodb+srv://fa21bscs7860:PyENalk60fjxwBrf@cluster0.nmg20.mongodb.net/?retryWrites=true&w=majority&appName=Cluster0" \
            asghar0017/nodejs-app
